### ISSUE TITLE
NVidia only?

### ISSUE THREAD

**Issue by stefan-reich** [sniklaus/pytorch-sepconv#28]
Too sad...

**Comment by sniklaus** [comment]
You can remove the `.cuda()` calls and run it on the CPU, albeit slower.

**Comment by ChameleonScales** [comment]
Hi,
Sorry for my lack of expertise but could you elaborate on how to do that?
There are 3 lines in run.py containing `cuda()`:
```
        netNetwork = Network().cuda().eval()
tenPreprocessedFirst = tenFirst.cuda().view(1, 3, intHeight, intWidth)
tenPreprocessedSecond = tenSecond.cuda().view(1, 3, intHeight, intWidth)
```
Do I need to comment out the concerned lines or just erase the `.cuda()`?

Also, do I need cupy anyway?
And if so, which provider for `opencl-nvidia` and `nvidia-utils` do I need between 340xx, 390xx, 418xx, 430xx, 435xx and 440xx ?

**Comment by sniklaus** [comment]
The adaptive separable convolution kernel is written in CUDA since PyTorch's built-in tensor operations would be quite a bit slower than this custom implementation that is invoked though CuPy.

https://github.com/sniklaus/sepconv-slomo/blob/5696b52db9a60dd030f2d3f82604f48a88f4a258/sepconv/sepconv.py#L8-L31

If you want to run this code on the CPU or different GPUs then you would have to rewrite the implementation of this adaptive separable convolution operator.

**Comment by ChameleonScales** [comment]
ok, sorry I thought you suggested an easy way to set up the program to run on CPU but rewriting the implementation is out of my scope.
