### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by LINSEVENQI** [sniklaus/pytorch-sepconv#41]
Hello! When the input video is 'car-turn.mp4'  , a frame interpolation sequence is obtained every two frames, and the output is the interpolated video. Why does the resolution of the video remain 640*360 not 1280*720, but the number of frames changes from 81 to 320?

**Comment by sniklaus** [comment]
This project does not perform super-resolution, only frame interpolation. As such, there is no reason why the output resolution should be greater than the input resolution.

Since this project performs video frame interpolation, frame-rate up-conversion to be more precise, the output will have more frames than the input. The provided script interpolates three additional frames between two given frames in a video. In other words, it produces two additional frames after each input frame and `320 ~ (1 + 3) * 81`.
