### ISSUE TITLE
nn.Upsampling is deprecated. Use nn.functional.interpolate instead.

### ISSUE THREAD

**Issue by LINSEVENQI** [sniklaus/pytorch-sepconv#44]
![image](https://user-images.githubusercontent.com/48674908/72047393-5f91fa00-32f5-11ea-8512-6776e14828a7.png)
Hello!I got this prompt when I ran your run.py! Why is this happening?And how can I solve it?

**Comment by sniklaus** [comment]
PyTorch recommends using `torch.nn.functional.interpolate` instead of `torch.nn.Upsampling` and may remove the latter in future versions: https://pytorch.org/docs/stable/nn.html#upsample

Please note that this is a warning, not an error. As such, the interpolation result should have been generated just fine. Closing for now, feel free to reopen in case the interpolation result is not generated.
