### ISSUE TITLE
Request_of_Pre-trained model and the script to train the model.

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [sniklaus/pytorch-sepconv#5]
@sniklaus ,Thanks for your sharing! Your work is very great!
Could you please offer the pre-trained model and the script to train the network?

**Comment by sdlpkxd** [comment]
The loading path of pre-trained models is in the install.bash file

**Comment by sniklaus** [comment]
Thank you for being interested in our work! Like @sdlpkxd mentioned, the pre-trained models are available through the `install.bash` script. As for the training, I am closing this issue since it is a duplicate of #3 and since there are a few forks who show how to do training with adaptive separable convolutions. This may also be a worthwhile read: https://arxiv.org/abs/1809.07759
