### ISSUE TITLE
How to train a model

### ISSUE THREAD

**Issue by littlefish12345** [sniklaus/pytorch-sepconv#51]
I want to train a model for anime but I don’t how to train a workable model.How can I do?

**Comment by sniklaus** [comment]
Thanks for your interest in our work! This issue seems like a duplicate of #3, so I am closing this for now. Please note that here are a few forks who show how to do training with adaptive separable convolutions (linked in the README.md, for example). This may also be a worthwhile read: https://arxiv.org/abs/1809.07759
